version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@2.0.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
  test:
    docker:
      - image: circleci/ruby:2.5.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: tests
          command: bin/rails test


workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - aws-ecr/build-and-push-image:
          repo: "ghactions"
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          cluster-name: 'Demo'
          service-name: 'demo-service'
          container-image-name-updates: 'container=demo,tag=${CIRCLE_SHA1}'
          family: 'demo'
          requires:
            - aws-ecr/build-and-push-image

